name: check-manifest
description: Run check-manifest
author: tj-actions
inputs:
  package-dir:
    description: 'Directory of the package'
    required: false
    default: ''
  args:
    description: 'Arguments passed to check-manifest'
    required: false
    default: '-v'
  version:
    description: 'Pinned version of check-manifest'
    required: true
    default: '0.46'

runs:
  using: 'composite'
  steps:
    - id: check-manifest
      run: |
        pip install -U check-manifest==${{inputs.version }}
        PACKAGE_DIR="${{ inputs.package-dir }}"
        if [[ -n $PACKAGE_DIR  ]]; then
          echo "Changing directory to $PACKAGE_DIR..."
          cd $PACKAGE_DIR
        fi
        check-manifest ${{ inputs.args }}
      shell: bash
branding:
  icon: check-square
  color: white
